<?php

/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;
use League\CommonMark\CommonMarkConverter;

/**
 * Class NewPost
 * @package Neoan3\Components
 */

class NewPost extends Unicore{
    /**
     * Route: new-post
     */
    function init(): void
    {
        $this
            ->uni('Demo')
            ->callback($this,'checkSubmit')
            ->hook('main', 'newPost')
            ->output();
    }
    function checkSubmit($uni)
    {
        if(isset($_POST['title'])){
            // content
            $converter = new CommonMarkConverter([
                'html_input' => 'strip',
                'allow_unsafe_links' => false,
            ]);
            // image
            var_dump($_FILES['image']);
        }
    }
}